config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  get 'users/edit/parent', to: 'users#edit_parent'
  patch 'users/edit/parent', to: 'users#update_parent'

  resources :projects, shallow: true do
    collection do
      get 'pinned'
    end

    member do
      # /project/1/pin --> pins#pin
      post 'pin', to: 'pins#pin'
      delete 'pin', to: 'pins#unpin'

      get 'students', to: 'projects#students'

      resources :chats
      resources :tasks do
        post :complete, on: :member
        post :incomplete, on: :member
      end
    end

    resources :resources
  end

  authenticated do
    # Redirect / => /dashboard when signed in
    root to: redirect('/projects'), as: 'homepage_authenticated'
  end

  root 'pages#home'
end

app/models/task.rb
class Task < ApplicationRecord
  include PublicActivity::Model
  tracked owner: :user, recipient: :project

  belongs_to :project
  belongs_to :user

  has_rich_text :content

  enum status: { incomplete: 0, complete: 1 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete, :incomplete]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.where(project: params[:id])
    @project = Project.find(params[:id])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @project = @task.project
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @project = Project.find(params[:id]) || @task.project
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.project ||= Project.find(params[:id])

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # POST /tasks/1/complete
  def complete
    if @task.update(status: :complete)
      redirect_to tasks_path(@task.project), notice: 'Task marked as completed'
    end
  end

  # POST /tasks/1/complete
  def incomplete
    if @task.update(status: :incomplete)
      redirect_to tasks_path(@task.project), notice: 'Task marked as incompleted'
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    path = project_path(@task.project)
    @task.destroy
    redirect_to path, notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:project_id, :title, :user_id, :due, :content)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
= form_with(model: task, local: true) do |form|
  - if task.errors.any?
    #error_explanation
      h2 #{pluralize(task.errors.count, "error")} prohibited this task from being saved:

      ul
        - task.errors.full_messages.each do |message|
          li= message

  .form-group
    = form.label :title, class: "form-label"
      | Task title

    = form.text_field :title, class: "form-control", placeholder: "Type the tasks's title in here&hellip;".html_safe

  .form-group
    = form.label :content, "Task description"
    = form.rich_text_area :content, placeholder: "You can write extra details in here"

  .form-group
    = form.label :user, class: "form-label"
      | Responsible for this task
    = form.select :user_id, User.all.map{ |u| [u.email, u.id] }, {}, { class: "custom-select", value: current_user.id }
    p.form-text.text-muted
      |
        This does not mean that they are responsible for doing the whole
        assignment! They can ask others for help and guidance. But, if this
        task isn't done by the deadline, they are accountable.

  .form-inline.mb-3: .container: .row
    = form.label :due, class: "form-label"
      | Due date
    = form.datetime_select :due, class: "custom-select"

  = form.submit class: "btn btn-primary"

  .card.mt-4: .card-body
    markdown:

      **Here are some things that make a task better**

      * Start with a verb
      * Keep the title short
      * Specific and clear

      Starting the name of your task with an action word (like "Write", "Call", "Brainstorm") helps your brain shift into "doing mode".

      If a task is longer than a few words, split it into multiple tasks.

      Writing out the full task name means you don't have to remember what it
      means later on. Good: "Create charts from data in Excel" Bad: "spreadsheet"

app/views/tasks/_task.html.slim
.card.mb-3
  div class=(local_assigns[:inline] ? "card-body c-inline-card" : "card-body")
    .form-check
      input.form-check-input(
        type="checkbox"
        id="#{task.id}-done"
        checked=task.complete?
        onclick="alert('Please use the button below to change the status of this task'); return false"
      )

      label.h5.form-check-label for="#{task.id}-done"
        - if task.content.present?
          span data-toggle="tooltip" title="This task has more details in its description."
            = octicon "file"

        - if current_page?(controller: 'tasks', action: 'show')
          = task.title
        - else 
          = link_to task.title, task

    .c-inline-card-props
      - if task.user.present? && !current_page?(action: 'show', controller: 'users')
        p.mb-0.text-muted
          = octicon "person"
          | In charge:
          =< link_to task.user.display_name, task.user, class: "text-dark text-decoration-none"

      - if task.due.present?
        p.mb-0.text-muted
          = octicon "clock"
          | Due in #{time_ago_in_words(task.due)} 

      / only show if not inline and not on user's page
      - unless local_assigns[:inline] || current_page?(action: 'show', controller: 'users')
        - if task.incomplete? 
          = button_to [:complete, task], class: "btn btn-link p-0"
            = octicon "check"
            | Mark as done
        - else
          = button_to [:incomplete, task], class: "btn btn-link text-danger p-0"
            = octicon "x"
            | Mark as not done

app/views/tasks/edit.html.slim
= render "shared/container"
  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @task.project.title, project_path(@task.project)
    - b.item "Tasks", tasks_path(@task.project)
    - b.item @task.title, tasks_path(@task)
    - b.item "Edit"

  h1.page-title Editing "#{@task.title}"

  = render 'form', task: @task

app/views/tasks/index.html.slim
= render "shared/container"

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Tasks"


  h1.page-title Tasks for #{@project.title}

  .d-flex.justify-content-center.w-100
    = link_to new_task_path, class: "btn btn-success btn-lg mb-2 text-align-center"
      = octicon "plus"
      | Add a new task

  = render @tasks

app/views/tasks/new.html.slim
= render "shared/container"
  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Tasks", tasks_path
    - b.item "New task"

  h1.page-title New Task

  = render 'form', task: @task

app/views/tasks/show.html.slim
= render "shared/container"
  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Tasks", tasks_path(@project)
    - b.item @task.title

  = render @task

  - if @task.content.present?
    .card.mb-3
      .card-header
        | Extra details
      .card-body
        == @task.content

  = link_to edit_task_path(@task), class: "btn btn-primary icon-btn btn-icon mb-2"
    = octicon "pencil"
    | Edit this task

  p.text-muted
    | Task created at: #{@task.created_at}
    br
    | Task last updated at: #{@task.updated_at}

  = button_to @task, method: 'delete', class: "btn text-danger btn-link px-0", data: { confirm: "Are you sure you want to delete this task?" }
    | Permenantly delete task&hellip;

  p.text-muted
    | Permenantly deleting tasks will show up on your profile.