config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  get 'users/edit/parent', to: 'users#edit_parent'
  patch 'users/edit/parent', to: 'users#update_parent'

  resources :projects, shallow: true do
    collection do
      get 'pinned'
    end

    member do
      # /project/1/pin --> pins#pin
      post 'pin', to: 'pins#pin'
      delete 'pin', to: 'pins#unpin'

      get 'students', to: 'projects#students'

      resources :chats
      resources :tasks do
        post :complete, on: :member
        post :incomplete, on: :member
      end
    end

    resources :resources
  end

  authenticated do
    # Redirect / => /dashboard when signed in
    root to: redirect('/projects'), as: 'homepage_authenticated'
  end

  root 'pages#home'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  # Defines permissions for each user role.
  #
  # == Not signed in:
  # If the user is not signed in, they cannot do *anything*. They are simply
  # redirected to the login / signup page
  #
  # == Studnets can manage most things
  # If the user is signed in as a student, they can:
  #
  #   * Read and pin all projects
  #   * Manage resources which they own
  #   * Read resources which they don't own
  #
  # == Teachers can do anything
  # If the user is signed in as a teacher, they can:
  # 
  #   * Manage projects
  #   * Manage resources
  #   
  # Read more here: https://github.com/CanCanCommunity/cancancan/blob/develop/docs/Defining-Abilities.md
  def initialize(user)
    return unless user.present?

    if user.student? or user.teacher?
      # Students and teachers can read and pin projects
      can [:read, :students, :pinned], Project
      can :manage, Pin, user: user

      # Stduent and teachers can read resources
      can :read, Resource
      # Stduent and teachers can manage their own resources
      can :manage, Resource, user: user

      # Students and teachers can discuss ideas
      can [:read, :create], Chat

      # Students and teachers can read milestones
      can :read, Milestone
    end

    if user.teacher?
      # Teachers can do anything they want
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates_presence_of :body

  scope :recent, -> {
    order(created_at: :desc).where.not(is_deleted: true)
  }
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  include PublicActivity::Model
  tracked({
    :owner => -> (controller, model) { controller.current_user },
    :recipient => :project
  })

  has_rich_text :description

  belongs_to :project

  validates_presence_of :date
  validates_presence_of :title
end

app/models/pin.rb
class Pin < ApplicationRecord
  include PublicActivity::Model
  tracked :owner => :user, :recipient => :project, :only => :create

  belongs_to :user
  belongs_to :project

  # A user can't have two pins for the same project
  validates_uniqueness_of :user, scope: :project
end

app/models/project.rb
class Project < ApplicationRecord
  include PublicActivity::Model
  tracked :owner => -> (controller, model) { controller.current_user }

  has_rich_text :brief
  has_many :resources, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :tasks, dependent: :destroy

  accepts_nested_attributes_for :pins

  # Returns all projects pinned by a user
  def self.pinned_by(user)
    joins(:pins).where(pins: { user: user, pinned: true })
  end

  # All students who have pinned this project
  def students
    User.includes(:pins).where(pins: { project: self, pinned: true })
  end

  def pinned_by?(user)
    pins.where(user: user, pinned: true).any?
  end

  def last_activity
    PublicActivity::Activity.where(recipient: self)
      .or(PublicActivity::Activity.where(trackable: self))
      .order(created_at: :desc)
      .first
  end

  def important_activities
    PublicActivity::Activity.where( recipient: self)
      .or(PublicActivity::Activity.where( trackable: self))
      .order(created_at: :desc)
      .limit(15)
  end
end

app/models/resource.rb
class Resource < ApplicationRecord
  include PublicActivity::Model
  tracked owner: :user, recipient: :project

  has_rich_text :content
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
  include PublicActivity::Model
  tracked owner: :user, recipient: :project

  belongs_to :project
  belongs_to :user

  has_rich_text :content

  enum status: { incomplete: 0, complete: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:student, :teacher, :admin]

  has_many :resources
  has_many :pins
  has_many :tasks

  def display_name
    self.email.split('@', 2).first.capitalize
  end

  def pinned_projects
    Project.pinned_by(self)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def pin
    @project = Project.find(params[:id])

    @pin = Pin.find_or_initialize_by(user: current_user, project: @project)
    @pin.pinned = true

    if @pin.save
      redirect_to @project, notice: 'Pinned project to dashboard'
    else
      redirect_to @project, alert: 'uh oh'
    end
  end

  def unpin
    @project = Project.find(params[:id])

    @pin = Pin.find_or_initialize_by(user: current_user, project: @project)
    @pin.pinned = false

    if @pin.save
      redirect_to @project, notice: 'Unpinned the project'
    else
      redirect_to @project, alert: 'uh oh'
    end
  end

  def pin_params
    params.require(:pin).permit(:user_id, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def debug_props
    {
      :current_user => current_user ? current_user.email : 'nil',
      :role => current_user ? current_user.role : 'nil'
    }
  end

  # Gravatar image
  def avatar(user, size=20)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    src = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    tag.img src: src, alt: user.email.downcase, class: "avatar rounded"
  end
end

app/helpers/breadcrumb_helper.rb
module BreadcrumbHelper
  class BreadcrumbBuilder
    include ActionView::Helpers::UrlHelper

    attr_accessor :breadcrumbs

    def initialize
      @breadcrumbs = ""
    end

    def self.build
      builder = new
      yield(builder)

      %Q(
        <nav aria-label="breadcrumbs" class="mb-4">
          <ol class="breadcrumb">
            #{builder.breadcrumbs}
          </ol>
        </nav>
      ).html_safe
    end

    def item(text, path=nil)
      if path
        @breadcrumbs += %Q(
          <li class="breadcrumb-item">
            <a href="#{url_for(path)}">#{text}</a>
          </li>
        )
      else
        @breadcrumbs += %Q(<li class="breadcrumb-item active">#{text}</li>)
      end
    end
  end

  def breadcrumbs(&block)
    BreadcrumbBuilder.build(&block)
  end
end

=begin
= breadcrummbs |b| do
  = b "" link
=end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/public_activity/resource/_create.slim
= octicon "plus", class: "text-success"
= link_to resource_path(activity.trackable_id), class: "text-body" do
  | added a resource to a project

app/views/public_activity/resource/_destroy.slim
= octicon "trash", width: 16, class: "text-danger"
| removed a resource

app/views/public_activity/resource/_update.slim
= octicon "pencil", class: "text-warning"
= link_to resource_path(activity.trackable_id), class: "text-body" do
  | updated a resource's details

app/views/resources/_form.html.slim
= form_with model: [project, resource], url: [project, resource], local: true do |f|
  - if resource.errors.any?
    .alert.alert-danger
      h2.h5
        => pluralize(resource.errors.count, "error")
        | prohibited this project from being saved:

      ul.mb-0
        - resource.errors.full_messages.each do |message|
          li= message

  .form-group
    = f.label :title, "Resource title"
    = f.text_field :title, placeholder: "Type the resource title here...", class: "form-control"

  .form-group
    = f.label :content, "Content"
    = f.rich_text_area :content, placeholder: "Type the knowledge you want to share with members of the project..."

  .form-text.text-muted
    | This resource is in the project
    = ' "' + @project.title + '"'

  .row.justify-content-end
    .col-auto
      = f.submit class: "btn btn-primary"

app/views/resources/_resource.html.slim
.list-group-item.list-group-item-action
  .row.justify-content-between
    .col-9
      p.mb-0= link_to resource.title, resource, class: "font-weight-bold text-body"
      p.mb-0= resource.content.to_plain_text.truncate(100)

      - unless params[:controller] == 'users' && params[:action] == 'show'
        p.mb-0.text-muted
          | Uploaded by 
          = link_to resource.user.display_name, resource.user, class: "text-dark"

      - unless params[:controller] == 'projects'
        p.mb-0
          | In project: 
          = link_to resource.project.title, resource.project

    .col-3.text-right
      p.text-secondary
        | last updated
        = ' ' + time_ago_in_words(resource.project.updated_at) + ' '
        | ago

app/views/resources/_summary_card.html.slim
= link_to project_resources_path(project), class: "text-reset text-decoration-none"
  .card.mb-3
    .card-header.font-weight-bold
      | Resources

    .card-body
      .row.flex-column.align-items-center
        = octicon "bookmark", width: 32
        p.p-3.mb-0.text-center
          | Share your work, see what your peers have found, and learn together

      - if project.resources.any?
        p.pt-3.font-weight-bold.border-top
          | Recently uploaded resources:
        ul.list-unstyled
          - project.resources.limit(3).each do |resource|
            = link_to resource, class: "text-decoration-none"
              li= resource.title

app/views/resources/edit.html.slim
= render "shared/container" do

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Resources", project_resources_path(@project)
    - b.item @resource.title, resource_path(@resource)
    - b.item "Edit resource details"


  h1.page-title
    | Edit resource details for
    em= ' ' + @resource.title

  / project:nil fixes some bug with nested resources and forms
  = render 'form', resource: @resource, project: nil

  .card.border-danger.mt-4
    .card-header Danger zone
    .card-body
      = button_to "Delete this resource...", @resource,
        data: { confirm: "Are you sure you want to delete '#{@resource.title}'?" },
        method: :destroy,
        class: "btn btn-danger"

app/views/resources/index.html.slim
= render "shared/container"

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Resources"


  h1.page-title Resources for #{@project.title}

  .d-flex.justify-content-center.w-100
    = link_to new_project_resource_path, class: "btn btn-success btn-lg mb-2 text-align-center"
      = octicon "plus"
      | Add a new resource

  = render @resources

app/views/resources/new.html.slim
= render "shared/container" do

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Resources", project_resources_path(@project)
    - b.item "Add a new resource"

  h1.page-title
    | Add a new resource to
    em= ' ' + @project.title

  = render 'form', project: @project, resource: @resource

app/views/resources/show.html.slim
= render "shared/container" do

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Resources", project_resources_path(@project)
    - b.item @resource.title

  - if notice
    .alert.alert-success= notice

  .row.justify-content-center.mb-3
    = link_to edit_resource_path(@resource), class: "text-dark" do
      = octicon "pencil"
      | Edit resource details

  h1.subpage-title= @resource.title

  p.text-muted.text-center
    | Added to project by
    = ' ' + @resource.user.email

  .card.mt-3
    .card-body
      == @resource.content

      - unless @resource.content.body?
        i No content
  

app/views/shared/_container.html.slim
.container.mt-3.mb-5
  - if notice
    .alert.alert-success#notice
      = notice

  .row.justify-content-center
    .col-12.col-md-10
      == yield

app/views/shared/_navbar.html.slim
nav.bg-light.py-3
  .container
    .row.justify-content-center
      .col-auto
        = link_to projects_path, class: "nav-item text-dark" do
          = octicon "home"
          | Home

      .col-auto
        = link_to "#", {\
            :id => "account",
            :class => "nav-item text-dark",
            :type => "button",
            :data => { :toggle => "dropdown" },
            :aria_haspopup => "true",
            :aria_expanded => "false",
          }
          = octicon "person"
          | Account

        - if current_user
          .dropdown-menu[aria-labelledby="edit_project_details" style="max-width: 500px"]
            = link_to user_path(current_user), class: "dropdown-item" do
              = octicon "smiley"
              | Profile (pinned projects, resources, activity) 
            = link_to edit_user_registration_path, class: "dropdown-item" do
              = octicon "settings", width: 16
              | Settings (email, password, parent's email)

            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              = octicon "sign-out", width: 16
              | Sign out