config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show

  get 'users/edit/parent', to: 'users#edit_parent'
  patch 'users/edit/parent', to: 'users#update_parent'

  resources :projects, shallow: true do
    collection do
      get 'pinned'
    end

    member do
      # /project/1/pin --> pins#pin
      post 'pin', to: 'pins#pin'
      delete 'pin', to: 'pins#unpin'

      get 'students', to: 'projects#students'

      resources :chats
      resources :tasks do
        post :complete, on: :member
        post :incomplete, on: :member
      end
    end

    resources :resources
  end

  authenticated do
    # Redirect / => /dashboard when signed in
    root to: redirect('/projects'), as: 'homepage_authenticated'
  end

  root 'pages#home'
end

app/models/project.rb
class Project < ApplicationRecord
  include PublicActivity::Model
  tracked :owner => -> (controller, model) { controller.current_user }

  has_rich_text :brief
  has_many :resources, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :tasks, dependent: :destroy

  accepts_nested_attributes_for :pins

  # Returns all projects pinned by a user
  def self.pinned_by(user)
    joins(:pins).where(pins: { user: user, pinned: true })
  end

  # All students who have pinned this project
  def students
    User.includes(:pins).where(pins: { project: self, pinned: true })
  end

  def pinned_by?(user)
    pins.where(user: user, pinned: true).any?
  end

  def last_activity
    PublicActivity::Activity.where(recipient: self)
      .or(PublicActivity::Activity.where(trackable: self))
      .order(created_at: :desc)
      .first
  end

  def important_activities
    PublicActivity::Activity.where( recipient: self)
      .or(PublicActivity::Activity.where( trackable: self))
      .order(created_at: :desc)
      .limit(15)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :students]
  load_and_authorize_resource

  def index
    @projects = Project.all.with_rich_text_brief

    unless @projects.any?
      redirect_to :new
    end
  end

  def pinned
    @projects = current_user.pinned_projects

    # TODO: find a better way to conditionally filter by pinned
    @pinned = true

    render "index"
  end

  def show
    @activities = @project.important_activities
  end

  def students
    @students = @project.students
    @activities = @project.important_activities
  end

  def new
    @project = Project.new
    @project.pins.build(user: current_user)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    input_params = params.require(:project).permit(
      :title,
      :brief,
      :pins_attributes => [
        :id,
        :pinned
      ]
    )

    input_params[:pins_attributes]["0"][:user_id] = current_user.id

    input_params
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_with model: project, local: true do |f| 
  - if project.errors.any?
    .alert.alert-danger
      p.mb-0
        |
          #{pluralize(project.errors.count, "error")} stopped this project from
          being saved:

      ul.mb-0
        - project.errors.full_messages.each do |message|
          li= message

  .form-group
    = f.label :title, "Project title"
    = f.text_field :title, placeholder: "Type the project title here...", class: "form-control"

  .form-group
    = f.label :brief, "A brief for the project"
    = f.rich_text_area :brief

  = f.fields_for :pins do |pins_form|
    .form-check
      = pins_form.check_box :pinned, class: "form-check-input"
      = pins_form.label :pinned, "Pin this project to your dashboard?", class: "form-check-label"

  .row.justify-content-end
    .col-auto
      = f.submit class: "btn btn-primary"

app/views/projects/_project.html.slim
= link_to project, class: "text-reset text-decoration-none" do
  .card.mb-2: .card-body.d-flex.flex-column.justify-content-center: .container
    .row
      - if project.pinned_by? current_user
        .col-auto.px-0.text-primary.pr-2
          = octicon "pin", data: { :toggle => "tooltip" }, title: "This project is pinned to your dashboard"

      .col.px-0
        b.text-body= project.title

        - if project.brief.body?
          p.mb-0.text-secondary== project.brief.to_plain_text.truncate(200)

app/views/projects/edit.html.slim
= render "shared/container" do

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path(@project)
    - b.item "Edit project details"

  p.text-center
    = link_to project_path do
      = octicon "arrow-left"
      | Back to project

  h1.page-title
    | Edit project details for
    em= ' ' + @project.title

  = render 'form', project: @project


  .card.border-danger.mt-4
    .card-header Danger zone
    .card-body
      = button_to "Delete this project...", @project,
        data: { confirm: "Are you sure you want to delete '#{@project.title}'?" },
        method: :delete,
        class: "btn btn-danger"

app/views/projects/index.html.slim
= render "shared/container" do

  h1.text-center.mt-4
    - unless @pinned
      | All projects
    - else
      = octicon "pin", width: 32
      | Your pinned projects 

  p.text-center
    - unless @pinned
      = link_to "Show only your pinned projects", pinned_projects_path, class: "text-secondary"
    - else
      = link_to "Show all projects", projects_path, class: "text-secondary"


  p.text-center
    = link_to new_project_path, class: "btn btn-success btn-lg" do
      = octicon "plus"
      | Create a new project

  = render @projects
      
  = link_to new_project_path, class: "text-dark bg-light card" do
    .card-body.d-flex.flex-column.text-center
      .new-project-icon
        = octicon "plus", width: 32
      b Create a new project

app/views/projects/new.html.slim
= render "shared/container" do

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item "New project"

  h1.page-title Create a new project

  = render "form", project: @project

app/views/projects/show.html.slim
= render "shared/container" do
  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title

  .row.justify-content-end
    .col-4.text-right
      .dropdown
        button.btn#edit_project_details[type="button" data-toggle="dropdown", aria-haspopup="true" aria-expanded="false" href="#"]
          = octicon "three-bars"

        .dropdown-menu[aria-labelledby="edit_project_details" style="max-width: 250px"]
          / Edit project
          - if can? :edit, @project
            = link_to edit_project_path, class: "dropdown-item" do
              = octicon "pencil"
              | Edit title, brief

          = link_to students_project_path, class: "dropdown-item" do
            = octicon "people"
            | View students

          / Pin/unpin project
          - if @project.pinned_by?(current_user)
            = link_to pin_project_path, class: "dropdown-item", method: :delete do
              = octicon "pin"
              | Unpin the project
          - else
            = link_to pin_project_path, class: "dropdown-item", method: :post do
              = octicon "pin"
              | Pin the project

          - if @project.last_activity
            p.text-muted.px-4.py-3.mb-0
              | Last edit was made
              = ' ' + time_ago_in_words(@project.last_activity.created_at) + ' '
              | ago.

  h1.page-title= @project.title

  - unless @project.pinned_by?(current_user)
    p.text-secondary.text-center
      | This project isn't in your dashboard. 
      = link_to pin_project_path, method: :post do
        = octicon "pin"
        | Pin the project

  - if @project.brief.body?
    .card.mb-3
      .card-header
        .row.justify-content-between.align-items-center
          .col-auto.font-weight-bold
            | Project brief
          - if can? :edit, @project
            .col-auto
              = link_to edit_project_path, data: { toggle: "tooltip" },
                title: "You can do this because you are a teacher"
                = octicon "pencil"
                | Edit project details
      .card-body== @project.brief


  .card.mb-3
    .card-header
      .row.justify-content-between.align-items-center
        .col.font-weight-bold
          = octicon "file"
          | Resources
        .col-auto
          = link_to project_resources_path(@project), class: "text-primary" do
            | View all resources&hellip;

    ul.list-group.list-group-flush
      - if @project.resources.any?
        = render @project.resources.limit(5)

      - else
        .list-group-item.text-center.text-secondary.font-italic
          | There are no resources in this project
  
  .card.mb-3
    .card-header
      .row.justify-content-between.align-items-center
        .col-auto.font-weight-bold
          = octicon "comment"
          | Chat
        .col-auto
          = link_to chats_path
            = octicon "paper-airplane"
            | Send chats&hellip;

    .card-body
      = render(@project.chats.recent.limit(3))

      - unless @project.chats.any?
        .text-center.text-secondary.font-italic
          | There are no chats in this project

      p.text-muted.border-top.px-2.pt-3.mt-4
        => link_to "The project chat", chats_path
        | is a place to ask questions, discuss ideas, and bounce ideas 
        | off eachother. 

  / =======
  /  TASKS
  / =======
  .card.mb-3
    .card-header
      .row.justify-content-between.align-items-center
        .col.font-weight-bold
          = octicon "check"
          | Tasks

        .col-auto
          = link_to new_task_path
            = octicon "plus"
            | Add a task

    .card-body
      - if @project.tasks.any?
        = render @project.tasks.limit(3), inline: true

        - if @project.tasks.size > 3
          = link_to tasks_path, class: "text-dark text-decoration-none"
            .card.bg-light: .card-body.d-flex.justify-content-center
              | #{@project.tasks.size - 3} more #{'task'.pluralize(@project.tasks.size - 3)}

        hr
        p #{@project.tasks.complete.size}/#{@project.tasks.size} tasks are done.
        progress.w-100 value=@project.tasks.complete.size max=@project.tasks.size

        = link_to "View all tasks &rarr;".html_safe, tasks_path
      - else
        .text-center
          p.mb-1
            |
              Here you can organise everything you need to do to get the
              project done. Start by adding a new task

          = link_to "Add a task", new_task_path


  .card.mt-3
    .card-body
      .card-title Recent project activity
      = render_activities @activities, layout: :activity

app/views/projects/students.html.slim
= render "shared/container"

  = breadcrumbs do |b|
    - b.item "Your projects", projects_path
    - b.item @project.title, project_path
    - b.item "Students"

  h1.subpage-title Students who pinned this project

  .list-group.mt-5
    - @students.each do |student|
      .list-group-item-action.list-group-item.cursor
        .row.justify-content-between.mb-2
          .col-auto
            p.mb-0
              = link_to student.display_name, student, class: "font-weight-bold text-body"
              = " (#{@activities.where(owner: student).size} recent activities)"
          .col-auto
            | pinned this project 
            => time_ago_in_words(student.pins.find_by(project: @project).created_at)
            | ago

        a.text-body data-toggle="collapse" href="#student_#{student.id}"
          = octicon "chevron-down"
          | Show activities
        .collapse id="student_#{student.id}"
          = render_activities @activities.where(owner: student), layout: :activity